language: go

notifications:
  email:
    recipients:
      - haitao.cao@bitmain.com
  on_success: change
  on_failure: always

install:

before_install:

script:
  - go build

before_deploy:

deploy:
